depends_on = None
"""Update enum values for GuidelineCategory

Revision ID: 2ff9739e891b
Revises: 9a35d8779a06
Create Date: 2025-11-05 18:39:51.366057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff9739e891b'
down_revision: Union[str, Sequence[str], None] = '9a35d8779a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
