depends_on = None
"""Make matrix rule columns nullable

Revision ID: 3d770880e031
Revises: 77db7511a235
Create Date: 2025-11-05 18:06:04.138748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d770880e031'
down_revision: Union[str, Sequence[str], None] = '77db7511a235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eligibility_matrix_rule', 'minLoanAmount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('eligibility_matrix_rule', 'maxLoanAmount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('eligibility_matrix_rule', 'minFicoScore',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('eligibility_matrix_rule', 'occupancyType',
               existing_type=postgresql.ENUM('PRIMARY', 'SECOND_HOME', 'INVESTMENT', name='occupancytype'),
               nullable=True)
    op.alter_column('eligibility_matrix_rule', 'loanPurpose',
               existing_type=postgresql.ENUM('PURCHASE', 'RATE_TERM', 'CASH_OUT', name='loanpurposetype'),
               nullable=True)
    op.alter_column('eligibility_matrix_rule', 'maxLtv',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eligibility_matrix_rule', 'maxLtv',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('eligibility_matrix_rule', 'loanPurpose',
               existing_type=postgresql.ENUM('PURCHASE', 'RATE_TERM', 'CASH_OUT', name='loanpurposetype'),
               nullable=False)
    op.alter_column('eligibility_matrix_rule', 'occupancyType',
               existing_type=postgresql.ENUM('PRIMARY', 'SECOND_HOME', 'INVESTMENT', name='occupancytype'),
               nullable=False)
    op.alter_column('eligibility_matrix_rule', 'minFicoScore',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('eligibility_matrix_rule', 'maxLoanAmount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('eligibility_matrix_rule', 'minLoanAmount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
