depends_on = None
"""Initial migration

Revision ID: 77db7511a235
Revises: 
Create Date: 2025-11-05 13:18:29.656866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77db7511a235'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lender',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('conversation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_program',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lenderId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('programCode', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sourceDocument', sa.String(), nullable=True),
    sa.Column('minLoanAmount', sa.Numeric(), nullable=True),
    sa.Column('maxLoanAmount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['lenderId'], ['lender.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lenderId', 'name', name='uq_lender_program')
    )
    op.create_index(op.f('ix_loan_program_programCode'), 'loan_program', ['programCode'], unique=True)
    op.create_table('chat_message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversationId', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AI', name='chatmessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversationId'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversationId', 'chat_message', ['conversationId'], unique=False)
    op.create_table('eligibility_matrix_rule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('loanProgramId', sa.String(), nullable=False),
    sa.Column('minLoanAmount', sa.Numeric(), nullable=False),
    sa.Column('maxLoanAmount', sa.Numeric(), nullable=False),
    sa.Column('minFicoScore', sa.Integer(), nullable=False),
    sa.Column('maxFicoScore', sa.Integer(), nullable=True),
    sa.Column('occupancyType', sa.Enum('PRIMARY', 'SECOND_HOME', 'INVESTMENT', name='occupancytype'), nullable=False),
    sa.Column('loanPurpose', sa.Enum('PURCHASE', 'RATE_TERM', 'CASH_OUT', name='loanpurposetype'), nullable=False),
    sa.Column('dscrValue', sa.String(), nullable=True),
    sa.Column('maxLtv', sa.Numeric(), nullable=False),
    sa.Column('reservesMonths', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['loanProgramId'], ['loan_program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loanProgramId', 'minLoanAmount', 'maxLoanAmount', 'minFicoScore', 'occupancyType', 'loanPurpose', 'dscrValue', name='uq_composite_rule')
    )
    op.create_index('idx_matrix_programId', 'eligibility_matrix_rule', ['loanProgramId'], unique=False)
    op.create_table('guideline',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('loanProgramId', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('LOAN_PURPOSE', 'EXCEPTIONS', 'PREPAYMENT_PENALTY', 'PRODUCT_TYPES', 'INTEREST_ONLY', 'LOAN_AMOUNTS', 'OCCUPANCY', 'PROPERTY_TYPES', 'PROPERTY_RESTRICTIONS', 'CASH_OUT', 'ACREAGE', 'APPRAISALS', 'DECLINING_MARKET', 'TRADELINES', 'HOUSING_HISTORY', 'CREDIT_EVENT_SEASONING', 'RESERVES', 'SELLER_CONCESSIONS', 'GIFT_FUNDS', 'SUBORDINATE_FINANCING', 'CITIZENSHIP', 'HOMEOWNER_EDUCATION', 'INELIGIBLE_STATES', 'INELIGIBLE_LOCATIONS', 'GEOGRAPHIC_RESTRICTIONS', 'FIRST_TIME_INVESTOR', 'FIRST_TIME_HOMEBUYER', 'INCOME_DOCUMENTATION', 'DTI', 'ASSET_UTILIZATION', 'MISCELLANEOUS', name='guidelinecategory'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sourceReference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['loanProgramId'], ['loan_program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_guideline_programId', 'guideline', ['loanProgramId'], unique=False)
    op.create_index(op.f('ix_guideline_category'), 'guideline', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guideline_category'), table_name='guideline')
    op.drop_index('idx_guideline_programId', table_name='guideline')
    op.drop_table('guideline')
    op.drop_index('idx_matrix_programId', table_name='eligibility_matrix_rule')
    op.drop_table('eligibility_matrix_rule')
    op.drop_index('idx_conversationId', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_loan_program_programCode'), table_name='loan_program')
    op.drop_table('loan_program')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('lender')
    # ### end Alembic commands ###
