depends_on = None
"""Update enum values for occupancy and loan purpose

Revision ID: 9a35d8779a06
Revises: c6477045c54c
Create Date: 2025-11-05 18:15:46.423842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a35d8779a06'
down_revision: Union[str, Sequence[str], None] = 'c6477045c54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
